import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/Components/Navbar";
import Sidebar from "@/Components/Sidebar";
import MainContent from "@/Components/MainContent";
import InstaSide from "@/Components/InstaSide";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    /*<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.globalContainer}>
        <main className={styles.main}>
          <Navbar />
          <Sidebar />
        </main>
      </div>
    </>*/

    <div className={styles.grid}>
      <div className={styles.item0}>
        <Navbar />
      </div>
      <div className={styles.item1}>
        <Sidebar />
      </div>
      <div className={styles.item2}>
        <MainContent />
      </div>
      <div className={styles.item3}>
        <InstaSide />
      </div>
    </div>
  );
}
